// models/Employee.js
import mongoose from "mongoose";

// All data Schema
const PCardFormAlDataSchema = new mongoose.Schema({
  Status: String,
  Bank_Name: String,
  Customer_Name: String,
  Father_Name: String,
  Mobile: String,
  Personal_Email: String,
  Pan_Card: String,
  Customer_Location: String,
  Company_Name: String,
  Dob: String,
  Login_Date: String,
  Gender: String,
  Religion: String,
  Income_Source: String,
  Marital_Status: String,
  Qualification: String,
  Property_Status: String,
  Aadhar_Card_No: String,
  Current_Address_Line1: String,
  Current_City: String,
  Current_Landmark: String,
  Current_State: String,
  Current_Pin: String,
  Permanent_Address_Line1: String,
  Permanent_City: String,
  Permanent_Landmark: String,
  Permanent_State: String,
  Permanent_Pin: String,
  Designation: String,
  Company_Address: String,
  Company_City: String,
  Company_State: String,
  Company_Pin: String,
  Annual_Ctc: String,
  Net_Salary: String,
  Caller_Name: String,
  TL_Name: String,
  Manager_Name: String,
  Card_Application_No: String,
  Card_Issue_Date: String,
  Rejection_Category: String,
  Rejection_Remark: String,
  Rejection_Date: String,
  email: String,
  Upload_Date: {
    type: Date,
    default: Date.now,
  },
});
const PCardPendingFormSchema = new mongoose.Schema({
  Status: String,
  Bank_Name: String,
  Customer_Name: String,
  Father_Name: String,
  Mobile: String,
  Personal_Email: String,
  Pan_Card: String,
  Customer_Location: String,
  Company_Name: String,
  Dob: String,
  Login_Date: String,
  Gender: String,
  Religion: String,
  Income_Source: String,
  Marital_Status: String,
  Qualification: String,
  Property_Status: String,
  Aadhar_Card_No: String,
  Current_Address_Line1: String,
  Current_City: String,
  Current_Landmark: String,
  Current_State: String,
  Current_Pin: String,
  Permanent_Address_Line1: String,
  Permanent_City: String,
  Permanent_Landmark: String,
  Permanent_State: String,
  Permanent_Pin: String,
  Designation: String,
  Company_Address: String,
  Company_City: String,
  Company_State: String,
  Company_Pin: String,
  Annual_Ctc: String,
  Net_Salary: String,
  Caller_Name: String,
  TL_Name: String,
  Manager_Name: String,
  Card_Application_No: String,
  Card_Issue_Date: String,
  Rejection_Category: String,
  Rejection_Remark: String,
  Rejection_Date: String,
  email: String,
  Upload_Date: {
    type: Date,
    default: Date.now,
  },
});

const PCardDisbursedDataSchema = new mongoose.Schema({
  Status: String,
  Bank_Name: String,
  Customer_Name: String,
  Father_Name: String,
  Mobile: String,
  Personal_Email: String,
  Pan_Card: String,
  Customer_Location: String,
  Company_Name: String,
  Dob: String,
  Login_Date: String,
  Gender: String,
  Religion: String,
  Income_Source: String,
  Marital_Status: String,
  Qualification: String,
  Property_Status: String,
  Aadhar_Card_No: String,
  Current_Address_Line1: String,
  Current_City: String,
  Current_Landmark: String,
  Current_State: String,
  Current_Pin: String,
  Permanent_Address_Line1: String,
  Permanent_City: String,
  Permanent_Landmark: String,
  Permanent_State: String,
  Permanent_Pin: String,
  Designation: String,
  Company_Address: String,
  Company_City: String,
  Company_State: String,
  Company_Pin: String,
  Annual_Ctc: String,
  Net_Salary: String,
  Caller_Name: String,
  TL_Name: String,
  Manager_Name: String,
  Card_Application_No: String,
  Card_Issue_Date: String,
  Rejection_Category: String,
  Rejection_Remark: String,
  Rejection_Date: String,
  email: String,
  Upload_Date: {
    type: Date,
    default: Date.now,
  },
});

const PCardRejectedDataSchema = new mongoose.Schema({
  Status: String,
  Bank_Name: String,
  Customer_Name: String,
  Father_Name: String,
  Mobile: String,
  Personal_Email: String,
  Pan_Card: String,
  Customer_Location: String,
  Company_Name: String,
  Dob: String,
  Login_Date: String,
  Gender: String,
  Religion: String,
  Income_Source: String,
  Marital_Status: String,
  Qualification: String,
  Property_Status: String,
  Aadhar_Card_No: String,
  Current_Address_Line1: String,
  Current_City: String,
  Current_Landmark: String,
  Current_State: String,
  Current_Pin: String,
  Permanent_Address_Line1: String,
  Permanent_City: String,
  Permanent_Landmark: String,
  Permanent_State: String,
  Permanent_Pin: String,
  Designation: String,
  Company_Address: String,
  Company_City: String,
  Company_State: String,
  Company_Pin: String,
  Annual_Ctc: String,
  Net_Salary: String,
  Caller_Name: String,
  TL_Name: String,
  Manager_Name: String,
  Card_Application_No: String,
  Card_Issue_Date: String,
  Rejection_Category: String,
  Rejection_Remark: String,
  Rejection_Date: String,
  email: String,
  Upload_Date: {
    type: Date,
    default: Date.now,
  },
});

const PCardFormAlData = mongoose.model(
  "PCardFormAlData",
  PCardFormAlDataSchema
);
const PCardPendingFormData = mongoose.model(
  "PCardPendingFormData",
  PCardPendingFormSchema
);
const PCardDisbursedData = mongoose.model(
  "PCardDisbursedData",
  PCardDisbursedDataSchema
);
// Create a model using the schema
const PCardRejectedData = mongoose.model(
  "PCardRejecteddata",
  PCardRejectedDataSchema
);

export {
  PCardFormAlData,
  PCardPendingFormData,
  PCardDisbursedData,
  PCardRejectedData,
};
